### ISSUE TITLE
target and module in tsconfig 

### ISSUE THREAD

**Issue by joshua1** [shavyg2/slick-for-svelte#12]
I found that this works "ONLY" if target is set to es5 and module to commonjs in tsconfig. when i try esnext for module or target (or any other combination)  , i only get the 404 page . why is that ?

**Comment by shavyg2** [comment]
any chance you can send a repository link showing the issue.

**Comment by joshua1** [comment]
You can use your starter project, just change target and module properties of tsconfig and see

**Comment by shavyg2** [comment]
Okay I will give it a look, it's likely because something I'm importing, I'll give it a look thank!!!

**Comment by joshua1** [comment]
Hi @shavyg2 any word on this or is the project abandoned?

**Comment by shavyg2** [comment]
no sorry, it's not abandoned, but i won't really be able to look at much until closer to the holiday season. A repo setup with the issue so i can focus and dive directly to it would be appreciated, but i understand other schedule as well. I will look into it when i get the chance.

**Comment by joshua1** [comment]
@shavyg2

**Comment by shavyg2** [comment]
yes i will look at this on sunday
