### ISSUE TITLE
LayoutProps not exported by factory

### ISSUE THREAD

**Issue by joshua1** [shavyg2/slick-for-svelte#13]
I am trying to add this lib to the official svelte starter and and get this error 
```
'LayoutProps' is not exported by node_modules/@slick-for/svelte/dist/src/slick-for-svelte-factory.js
```
Even though decorators are imported in slick-for-svelte-factory file. Any idea why this is happening ?

**Comment by shavyg2** [comment]
Try updating slick, you might be on an older version also if you update use this in the template 
Use the base template, that's what the unit test runs against
https://slick-for.com/svelte/docs/template
